# Generated by Django 5.2.7 on 2025-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fragrance_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Key_Notes', models.TextField(blank=True, null=True)),
                ('Characteristics', models.TextField(blank=True, null=True)),
                ('Fragrance_Image', models.ImageField(blank=True, null=True, upload_to='Uploads')),
            ],
        ),
    ]
