# Generated by Django 5.2.7 on 2025-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perfume_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Fragrance_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.PositiveIntegerField()),
                ('Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Expire_Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
