# Generated by Django 5.2.7 on 2025-11-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0002_perfumesdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfumesdb',
            old_name='Expire_Date',
            new_name='Expiry_Date',
        ),
    ]
