# Generated by Django 5.2.7 on 2025-11-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0003_rename_expire_date_perfumesdb_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumesdb',
            name='Perfume_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads'),
        ),
    ]
