# Generated by Django 5.2.7 on 2025-11-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Perfume_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('Total_Price', models.PositiveIntegerField()),
                ('Perfume_Image', models.ImageField(blank=True, null=True, upload_to='Cart Images')),
            ],
        ),
    ]
