# Generated by Django 5.2.7 on 2025-12-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_Code', models.PositiveIntegerField()),
                ('Phone', models.PositiveIntegerField()),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Total_Price', models.PositiveIntegerField()),
            ],
        ),
    ]
