# Generated by Django 5.2.7 on 2025-12-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_orderdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='User_name',
            new_name='User_Name',
        ),
    ]
